/* eslint-disable @typescript-eslint/no-explicit-any */
import { Button } from "../../../../components/ui/button";
import { Card } from "../../../../components/ui/card";
import { awardTypeLabels, getMembers, parseWeekDate } from "../../../../lib/actions/admin-common";
import { deleteAwardAction, getAwards, saveAwardAction } from "../../../../lib/actions/awards";

export default async function AwardsPage({ searchParams }: { searchParams?: Promise<{ week?: string }> }) {
  const params = await searchParams; const weekDate = parseWeekDate(params?.week); const [awards, members] = await Promise.all([getAwards(weekDate), getMembers()]);
  return <div className="space-y-4"><div><p className="text-sm text-text-2">{weekDate}</p><h1 className="text-2xl font-semibold">獎項管理</h1></div><Card className="p-4"><form action={saveAwardAction} className="grid gap-3 md:grid-cols-4"><input type="hidden" name="week_date" value={weekDate} /><select name="recipient_id" className="rounded border border-border p-2"><option value="">得獎人</option>{members.map((m) => <option key={m.id} value={m.id}>{m.chinese_name}</option>)}</select><select name="award_type" className="rounded border border-border p-2">{Object.entries(awardTypeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><input name="description" className="rounded border border-border p-2" placeholder="描述" /><Button type="submit">新增獎項</Button></form></Card><div className="grid gap-3">{awards.map((award: any) => <Card className="p-4" key={award.id}><form action={saveAwardAction} className="grid gap-3 md:grid-cols-5"><input type="hidden" name="id" value={award.id} /><input type="hidden" name="week_date" value={weekDate} /><select name="recipient_id" className="rounded border border-border p-2" defaultValue={award.recipient_id || ""}><option value="">得獎人</option>{members.map((m) => <option key={m.id} value={m.id}>{m.chinese_name}</option>)}</select><select name="award_type" className="rounded border border-border p-2" defaultValue={award.award_type}>{Object.entries(awardTypeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><input name="description" className="rounded border border-border p-2 md:col-span-2" defaultValue={award.description || ""} /><Button type="submit" variant="secondary">更新</Button></form><form action={deleteAwardAction} className="mt-2"><input type="hidden" name="id" value={award.id} /><Button type="submit" variant="ghost">刪除</Button></form></Card>)}</div></div>;
}
